import Sidebar from '../../components/base/SideBar'
import TopBar from '../../components/base/TopBar'
import NextAuthSessionProvider from '../providers/sessionProvider'
// import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'CondoHelp',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthSessionProvider>
          <section className='flex'>
            <Sidebar />
            <main className='w-full p-3'>
              <TopBar />
              <div className='pl-2 pr-2'>
                {children}
              </div>
            </main>
          </section>
        </NextAuthSessionProvider>
      </body>
    </html>
  )
}
